import type { JobSpyJob } from '@/lib/jobspy-api'

/** Preview listings shown when the job API is offline so the board layout can be reviewed. */
export const SAMPLE_JOBSPY_JOBS: JobSpyJob[] = [
  {
    id: 'sample-job-1',
    title: 'Junior Software Engineer Intern',
    company_name: 'Nimbus Labs',
    location_display: 'Bengaluru, Karnataka',
    city: 'Bengaluru',
    state: 'Karnataka',
    site: 'linkedin',
    is_remote: false,
    tag_status: 'complete',
    key_skills: ['Python', 'Git', 'SQL', 'REST APIs'],
    min_amount: 15000,
    max_amount: 25000,
    currency: 'INR',
    job_type: 'Internship',
    date_posted: '2026-07-14',
    job_url: 'https://example.com/jobs/nimbus-intern',
    description:
      'Work with mentors on small product features, write tests, and learn the full development cycle. Ideal for students finishing a CS or related degree.',
    experience_band: 'internship',
  },
  {
    id: 'sample-job-2',
    title: 'Fresher Data Analyst',
    company_name: 'BrightMetrics',
    location_display: 'Hyderabad, Telangana',
    city: 'Hyderabad',
    state: 'Telangana',
    site: 'naukri',
    is_remote: true,
    tag_status: 'complete',
    key_skills: ['Excel', 'SQL', 'Power BI', 'Python'],
    min_amount: 300000,
    max_amount: 450000,
    currency: 'INR',
    job_type: 'Full-time',
    date_posted: '2026-07-16',
    job_url: 'https://example.com/jobs/brightmetrics-analyst',
    description:
      'Build dashboards, clean datasets, and support weekly business reviews. Training provided for Power BI and SQL best practices.',
    experience_band: 'fresher',
  },
  {
    id: 'sample-job-3',
    title: 'Frontend Developer (Entry Level)',
    company_name: 'PixelForge',
    location_display: 'Pune, Maharashtra',
    city: 'Pune',
    state: 'Maharashtra',
    site: 'indeed',
    is_remote: false,
    tag_status: 'complete',
    key_skills: ['React', 'TypeScript', 'CSS', 'JavaScript'],
    min_amount: 350000,
    max_amount: 500000,
    currency: 'INR',
    job_type: 'Full-time',
    date_posted: '2026-07-12',
    job_url: 'https://example.com/jobs/pixelforge-frontend',
    description:
      'Ship UI improvements for a B2B SaaS product. You will pair with senior engineers and own small components end to end.',
    experience_band: 'fresher',
  },
  {
    id: 'sample-job-4',
    title: 'SQL / Backend Trainee',
    company_name: 'Indra Cloud Services',
    location_display: 'Chennai, Tamil Nadu',
    city: 'Chennai',
    state: 'Tamil Nadu',
    site: 'foundit',
    is_remote: false,
    tag_status: 'complete',
    key_skills: ['SQL', 'PostgreSQL', 'Python', 'APIs'],
    min_amount: 20000,
    max_amount: 30000,
    currency: 'INR',
    job_type: 'Internship',
    date_posted: '2026-07-18',
    job_url: 'https://example.com/jobs/indra-sql-trainee',
    description:
      'Support data pipelines and simple API endpoints. Strong SQL fundamentals required; cloud experience is a plus.',
    experience_band: 'internship',
  },
  {
    id: 'sample-job-5',
    title: 'QA Automation Intern',
    company_name: 'AssureSoft',
    location_display: 'Remote, India',
    city: null,
    state: null,
    site: 'linkedin',
    is_remote: true,
    tag_status: 'complete',
    key_skills: ['Selenium', 'Java', 'Test Cases', 'Git'],
    min_amount: 12000,
    max_amount: 20000,
    currency: 'INR',
    job_type: 'Internship',
    date_posted: '2026-07-10',
    job_url: 'https://example.com/jobs/assuresoft-qa',
    description:
      'Write and maintain automation scripts for regression suites. Learn CI basics and defect tracking in a product team.',
    experience_band: 'internship',
  },
  {
    id: 'sample-job-6',
    title: 'Junior Full Stack Developer',
    company_name: 'Orbit Retail Tech',
    location_display: 'Mumbai, Maharashtra',
    city: 'Mumbai',
    state: 'Maharashtra',
    site: 'google',
    is_remote: false,
    tag_status: 'complete',
    key_skills: ['Node.js', 'React', 'MongoDB', 'REST'],
    min_amount: 400000,
    max_amount: 600000,
    currency: 'INR',
    job_type: 'Full-time',
    date_posted: '2026-07-15',
    job_url: 'https://example.com/jobs/orbit-fullstack',
    description:
      'Build features across the stack for an e-commerce platform. Mentorship and code reviews every sprint.',
    experience_band: '1plus',
  },
]
